name: Build chiaki-ng macOSX arm64

on:
  workflow_dispatch:

jobs:
  build-mac_arm64_github:
    name: Build macOSX arm64 version Github
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install protobuf
        run: |
          pip3 install --user 'protobuf>=5,<6' --break-system-packages
      - name: Install brew dependencies
        run: |
          brew update
          brew uninstall pkgconfig || true
          brew install --force streetpea/streetpea/chiaki-ng-qt@6 ffmpeg pkgconfig opus openssl cmake ninja nasm sdl2 protobuf@29 speexdsp libplacebo wget python-setuptools json-c miniupnpc

      - name: Configure chiaki-ng
        run: |
          cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCHIAKI_ENABLE_CLI=OFF -DCHIAKI_ENABLE_STEAMDECK_NATIVE=OFF -DCMAKE_PREFIX_PATH="$(brew --prefix)/opt/@openssl@3;$(brew --prefix)/opt/chiaki-ng-qt@6;$(brew --prefix)/opt/protobuf@29"

      - name: Build chiaki-ng
        run: |
          export CPATH=$(brew --prefix)/opt/ffmpeg/include
          cmake --build build --config Release --clean-first --target chiaki

      - name: Deploy chiaki-ng
        run: |
          cp -a build/gui/chiaki.app chiaki-ng.app
          cp scripts/qtwebengine_import.qml gui/src/qml/
          $(brew --prefix)/opt/chiaki-ng-qt@6/bin/macdeployqt chiaki-ng.app -qmldir="$PWD/gui/src/qml" -libpath=$(brew --prefix)/lib
          mkdir -p chiaki-ng.app/Contents/Resources/vulkan/icd.d
          wget https://github.com/KhronosGroup/MoltenVK/releases/download/v1.2.11-artifacts/MoltenVK-macos.tar && tar xf MoltenVK-macos.tar
          cp MoltenVK/MoltenVK/dylib/macOS/* chiaki-ng.app/Contents/Resources/vulkan/icd.d
          $(brew --prefix)/opt/chiaki-ng-qt@6/bin/macdeployqt chiaki-ng.app -qmldir="$PWD/gui/src/qml" -libpath=$(brew --prefix)/lib
          if [[ -d chiaki-ng.app/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app ]]
          then
            ln -s ../../../../../../../Frameworks chiaki-ng.app/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents
          fi
          ln -s libvulkan.1.dylib chiaki-ng.app/Contents/Frameworks/vulkan
          codesign --force --entitlements gui/entitlements.xml --deep --sign - chiaki-ng.app
          hdiutil create -srcfolder chiaki-ng.app chiaki-ng.dmg
          codesign --force --entitlements gui/entitlements.xml --deep --sign - chiaki-ng.dmg

      - name: Upload chiaki-ng Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chiaki-ng-macos_arm64-Release
          path: chiaki-ng.dmg
          if-no-files-found: error
          retention-days: 7
