name: Build chiaki-ng msys2 Windows

on:
  workflow_dispatch:

jobs:
  build-windows_x64-msys2:
    name: Build windows msys2 version
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Disable autocrlf
        shell: pwsh
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: git
          pacboy: >-
            ca-certificates:p
            cc:p
            cmake:p
            curl:p
            diffutils:p
            fast_float:p
            fftw:p
            hidapi:p
            json-c:p
            lcms2:p
            libdovi:p
            libplacebo:p
            meson:p
            miniupnpc:p
            nasm:p
            ninja:p
            openssl:p
            opus:p
            pkgconf:p
            protobuf-c:p
            python:p
            python-glad:p
            python-jinja:p
            python-pip:p
            qt5-declarative:p
            qt6-base:p
            qt6-declarative:p
            qt6-svg:p
            SDL2:p
            shaderc:p
            speexdsp:p
            spirv-cross:p
            vulkan:p
            vulkan-headers:p
            
      - name: Install python protobuf and zip
        run: |
          pip install protobuf
          pacman -S zip git make unzip --noconfirm

      - name: Build libbplacebo
        run: |
          scripts/build-libplacebo-windows.sh

      - name: Setup ffmpeg
        run: |
          curl -LO https://github.com/r52/FFmpeg-Builds/releases/download/latest/ffmpeg-n7.1-latest-win64-gpl-shared-7.1.zip
          unzip ffmpeg-n7.1-latest-win64-gpl-shared-7.1.zip
          cp -a "ffmpeg-n7.1-latest-win64-gpl-shared-7.1/bin/." /mingw64/bin
          cp -a "ffmpeg-n7.1-latest-win64-gpl-shared-7.1/include/." /mingw64/include
          cp -a "ffmpeg-n7.1-latest-win64-gpl-shared-7.1/lib/." /mingw64/lib

      - name: Configure chiaki-ng
        run: |
          cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCHIAKI_ENABLE_CLI=OFF

      - name: Build chiaki-ng
        run: |
          cmake --build build --config Release --clean-first --target chiaki
          
      - name: Deploy qt6-base:p
        run: |
          mkdir chiaki-ng-Win
          cp build/gui/chiaki.exe chiaki-ng-Win
          cp build/third-party/cpp-steam-tools/libcpp-steam-tools.dll chiaki-ng-Win/
          ls /mingw64/bin/
          cp /mingw64/bin/libcrypto-*.dll chiaki-ng-Win/
          cp /mingw64/bin/libssl-*.dll chiaki-ng-Win/
          cp /mingw64/bin/SDL2.dll chiaki-ng-Win/
          cp /mingw64/bin/avcodec-*.dll chiaki-ng-Win/
          cp /mingw64/bin/avutil-*.dll chiaki-ng-Win/
          cp /mingw64/bin/avformat-*.dll chiaki-ng-Win/
          cp /mingw64/bin/libgcc_s_seh-*.dll chiaki-ng-Win/
          cp /mingw64/bin/libopus-*.dll chiaki-ng-Win/
          cp /mingw64/bin/libfftw3-*.dll chiaki-ng-Win/
          cp /mingw64/bin/libplacebo-*.dll chiaki-ng-Win/
          cp /mingw64/bin/libspeexdsp-*.dll chiaki-ng-Win/
          cp /mingw64/bin/libstdc++-*.dll chiaki-ng-Win/
          cp /mingw64/bin/libbz2-*.dll chiaki-ng-Win/
          cp /mingw64/bin/libiconv-*.dll chiaki-ng-Win/
          cp /mingw64/bin/libhidapi-*.dll chiaki-ng-Win/
          cp /mingw64/bin/zlib1.dll chiaki-ng-Win/
          cp /mingw64/bin/libglib-*.dll chiaki-ng-Win/
          cp /mingw64/bin/libgobject-*.dll chiaki-ng-Win/
          cp /mingw64/bin/liblzma-*.dll chiaki-ng-Win/
          cp /mingw64/bin/libintl-*.dll chiaki-ng-Win/
          cp /mingw64/bin/libwinpthread-*.dll chiaki-ng-Win/
          cp /mingw64/bin/liblcms2-*.dll chiaki-ng-Win/
          cp /mingw64/bin/dovi.dll chiaki-ng-Win/
          cp /mingw64/bin/libshaderc_shared.dll chiaki-ng-Win/
          cp /mingw64/bin/libspirv-cross-c-shared.dll chiaki-ng-Win/
          cp /mingw64/bin/libssh2-*.dll chiaki-ng-Win/
          cp /mingw64/bin/libbrotlienc.dll chiaki-ng-Win/
          cp /mingw64/bin/libbrotlidec.dll chiaki-ng-Win/
          cp /mingw64/bin/libfreetype-*.dll chiaki-ng-Win/
          cp /mingw64/bin/libgmp-*.dll chiaki-ng-Win/
          cp /mingw64/bin/libidn2-*.dll chiaki-ng-Win/
          cp /mingw64/bin/libpng*.dll chiaki-ng-Win/
          cp /mingw64/bin/libharfbuzz-*.dll chiaki-ng-Win/
          cp /mingw64/bin/libmd4c.dll chiaki-ng-Win/
          cp /mingw64/bin/libzstd.dll chiaki-ng-Win/
          cp /mingw64/bin/libicuuc*.dll chiaki-ng-Win/
          cp /mingw64/bin/libb2-*.dll chiaki-ng-Win/
          cp /mingw64/bin/libdouble-conversion.dll chiaki-ng-Win/
          cp /mingw64/bin/libicuin*.dll chiaki-ng-Win/
          cp /mingw64/bin/libpcre2-*.dll chiaki-ng-Win/
          cp /mingw64/bin/libp11-kit-*.dll chiaki-ng-Win/
          cp /mingw64/bin/libtasn1-*.dll chiaki-ng-Win/
          cp /mingw64/bin/libunistring-*.dll chiaki-ng-Win/
          cp /mingw64/bin/libfontconfig-*.dll chiaki-ng-Win/
          cp /mingw64/bin/libffi-*.dll chiaki-ng-Win/
          cp /mingw64/bin/libgio-*.dll chiaki-ng-Win/
          cp /mingw64/bin/libsharpyuv-*.dll chiaki-ng-Win/
          cp /mingw64/bin/libbrotlicommon.dll chiaki-ng-Win/
          cp /mingw64/bin/libicudt*.dll chiaki-ng-Win/
          cp /mingw64/bin/libgraphite*.dll chiaki-ng-Win/
          cp /mingw64/bin/libexpat*.dll chiaki-ng-Win/
          cp /mingw64/bin/libgmodule-*.dll chiaki-ng-Win/
          cp /mingw64/bin/libgomp-*.dll chiaki-ng-Win/
          cp /mingw64/bin/libminiupnpc.dll chiaki-ng-Win/
          cp /mingw64/bin/libpsl-*.dll chiaki-ng-Win/
          cp /mingw64/bin/libjson-c-*.dll chiaki-ng-Win/
          cp /mingw64/bin/swresample-*.dll chiaki-ng-Win/
          /mingw64/bin/windeployqt6.exe --no-translations --qmldir=$PWD/gui/src/qml --release chiaki-ng-Win/chiaki.exe
          cp -R /mingw64/share/qt6/qml/QtQuick chiaki-ng-Win/qml/
          cp -R /mingw64/share/qt6/qml/QtQml/WorkerScript/ chiaki-ng-Win/qml/QtQml/
          cp /mingw64/bin/Qt6QmlWorkerScript.dll chiaki-ng-Win/
          zip -r chiaki-ng-Win.zip chiaki-ng-Win/

      - name: Upload chiaki-ng Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chiaki-ng-win_x64-MSYS2-Release
          path: chiaki-ng-Win.zip
          if-no-files-found: error
          retention-days: 7
          

